module.exports = {
  kat0: {
    p0: undefined,
    p1: undefined,
    p2: undefined,
    p3: undefined,
    p4: undefined,
    p5: undefined,
  },
  kat1: {
    p0: undefined,
    p1: undefined,
    p2: undefined,
    p3: undefined,
    p4: undefined,
    p5: undefined,
    p6: undefined,
    p7: undefined,
  },
  kat2: {
    p0: undefined,
    p1: undefined,
    p2: undefined,
    p3: undefined,
    p4: undefined,
    p5: undefined,
    p6: undefined,
    p7: undefined,
    p8: undefined,
    p9: undefined,
  },
  kat3: {
    p0: undefined,
    p1: undefined,
    p2: undefined,
    p3: undefined,
    p4: undefined,
  },
  kat4: {
    p0: undefined,
    p1: undefined,
    p2: undefined,
    p3: undefined,
    p4: undefined,
    p5: undefined,
    p6: undefined,
  },
  kat5: {
    p0: undefined,
    p1: undefined,
    p2: undefined,
    p3: undefined,
    p4: undefined,
    p5: undefined,
    p6: undefined,
    p7: undefined,
    p8: undefined,
    p9: undefined,
  },
  kat6: {
    p0: undefined,
    p1: undefined,
    p2: undefined,
    p3: undefined,
    p4: undefined,
    p5: undefined,
  },
  kat7: {
    p0: undefined,
    p1: undefined,
    p2: undefined,
    p3: undefined,
    p4: undefined,
  },
  kat8: {
    p0: undefined,
    p1: undefined,
    p2: undefined,
    p3: undefined,
    p4: undefined,
    p5: undefined,
    p6: undefined,
    p7: undefined,
    p8: undefined,
  },
  kat9: { p0: undefined, p1: undefined, p2: undefined },
  kat10: {
    p0: undefined,
    p1: undefined,
    p2: undefined,
    p3: undefined,
    p4: undefined,
    p5: undefined,
    p6: undefined,
    p7: undefined,
    p8: undefined,
    p9: undefined,
    p10: undefined,
  },
};
