module.exports = {
  kat0: {
    p0: { status: 'accept', note: '' },
    p1: { status: 'reject', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
  },
  kat1: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
  },
  kat2: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat3: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat4: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
  },
  kat5: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat6: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
  },
  kat7: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat8: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
  },
  kat9: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
  },
  kat10: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
    p10: { status: '', note: '' },
  },
};
